In [1]:
import pandas as pd
import numpy as np

# Data preparation

In [2]:
df = pd.read_csv("../../data/Iris.csv")
df = df.iloc[[1, 51, 101]]

df.head()

Id  sepal_length  sepal_width  petal_length  petal_width  \
1      2           4.9          3.0           1.4          0.2   
51    52           6.4          3.2           4.5          1.5   
101  102           5.8          2.7           5.1          1.9   

             species  
1        Iris-setosa  
51   Iris-versicolor  
101   Iris-virginica

In [3]:
y = pd.get_dummies(df.species).values
x = df.drop(["Id", "species"], axis=1).values

In [4]:
print(x)
print()
print(y)

[[4.9 3.  1.4 0.2]
 [6.4 3.2 4.5 1.5]
 [5.8 2.7 5.1 1.9]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# Parameters

In [5]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [6]:
learning_rate = 0.1
N = y.size

n_input = 4
n_hidden = 2
n_output = 3

In [7]:
np.random.seed(10)

weights_1 = np.random.normal(scale=0.5, size=(n_input, n_hidden)).round(1)   # (4, 2)
weights_2 = np.random.normal(scale=0.5, size=(n_hidden, n_output)).round(1)  # (2, 3)

In [8]:
print(weights_1)
print()
print(weights_2)

[[ 0.7  0.4]
 [-0.8 -0. ]
 [ 0.3 -0.4]
 [ 0.1  0.1]]

[[ 0.  -0.1  0.2]
 [ 0.6 -0.5  0.5]]


# Feedforward and Backpropagation

In [9]:
# feedforward
hidden_layer_in = np.dot(x, weights_1).round(2)
hidden_layer_out = sigmoid(hidden_layer_in).round(2)

output_layer_in = np.dot(hidden_layer_out, weights_2).round(2)
output_layer_out = sigmoid(output_layer_in).round(2)

# backpropagation
output_error = (output_layer_out - y).round(2)
output_delta = (output_error * output_layer_out * (1 - output_layer_out)).round(2)

hidden_error = np.dot(output_delta, weights_2.T).round(3)
hidden_delta = (hidden_error * hidden_layer_out * (1 - hidden_layer_out)).round(3)

# weight updates
weights_1_update = (np.dot(x.T, hidden_delta) / N).round(3)
weights_2_update = (np.dot(hidden_layer_out.T, output_delta) / N).round(3)

In [10]:
mse = ((output_layer_out - y)**2).sum() / (2*N)
mse

0.13844444444444445

In [11]:
print(hidden_layer_in)
print()
print(hidden_layer_out)
print()

print(output_layer_in)
print()
print(output_layer_out)
print()

[[1.47 1.42]
 [3.42 0.91]
 [3.62 0.47]]

[[0.81 0.81]
 [0.97 0.71]
 [0.97 0.62]]

[[ 0.49 -0.49  0.57]
 [ 0.43 -0.45  0.55]
 [ 0.37 -0.41  0.5 ]]

[[0.62 0.38 0.64]
 [0.61 0.39 0.63]
 [0.59 0.4  0.62]]



In [12]:
print(output_error)
print()
print(output_delta)
print()

print(hidden_error)
print()
print(hidden_delta)
print()

[[-0.38  0.38  0.64]
 [ 0.61 -0.61  0.63]
 [ 0.59  0.4  -0.38]]

[[-0.09  0.09  0.15]
 [ 0.15 -0.15  0.15]
 [ 0.14  0.1  -0.09]]

[[ 0.021 -0.024]
 [ 0.045  0.24 ]
 [-0.028 -0.011]]

[[ 0.003 -0.004]
 [ 0.001  0.049]
 [-0.001 -0.003]]



In [13]:
print(weights_2_update)
print()
print(weights_1_update)
print()

[[0.023 0.003 0.02 ]
 [0.013 0.003 0.019]]

[[0.002 0.031]
 [0.001 0.015]
 [0.    0.022]
 [0.    0.007]]

